name = "FiniteElementAnalysis"
uuid = "c185b64a-f1cc-46a9-b3a8-aef9edaf193f"
authors = ["Joby M. Anthony III"]
version = "0.0.0-dev"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
julia       = "1"
LinearSolve = "1, 2"
Symbolics   = "5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
